---
title: 'Parque Operativo: Categoría: IPOD'
author: "Tecnología & Sistemas"
date: "`r Sys.Date()`"
output:
  html_notebook: default
editor_options:
  chunk_output_type: inline
---

## Generales

El presente documento responde las siguientes preguntas sobre nuestro parque operativo de IPODs: 

- ¿Cuántos IPODs tenemos desplegados? ¿cuántos debemos tener? ¿cuántos nos hacen falta?
- ¿En qué condición se encuentran los equipos desplegados? ¿cómo medimos la salud del parque operativo?
- ¿Cuántos IPODs han tenido reemplazo de batería? De esos, ¿cuántos fueron reintegrados? ¿cuántos fueron descartados? ¿cuántos no han tenido reemplazo?

Para responder estas preguntas, la fuente principal de información será el sistema de gestión de activos **Snipe-IT**, implementado en Junio del 2021. La información anterior a este período ha sido obtenida de los formularios de control, cuya data ha sido digitada en el sistema. 

Con esto, se consigue describir la situación actual del parque operativo y su comportamiento histórico. Logrado esto, se apoya la toma de decisiones certeras y oportunas respecto al parque de IPODs, para lograr un balance costo-operativo.

A continuación, se contestan las preguntas planteadas.

## ¿Cuántos IPODs tenemos desplegados?
#### ¿cuántos debemos tener? ¿cuántos nos hacen falta?

```{r}
source("./lib/assets.R")
ipods <- assets.by_category(cat = "IPOD")
requeridos <- sum(ipods$req_quantity)
desplegados <- sum(ipods$total)
necesitados <- requeridos-desplegados
cobertura <- round((desplegados/requeridos)*100, digits = 2)
```

Tenemos **`r desplegados`** equipos desplegados de un total de **`r requeridos`** equipos requeridos para la operación. Esto representa una cobertura de **`r cobertura`%**. Necesitamos desplegar **`r necesitados`** equipos para lograr el *100%* de cobertura operativa.

La siguiente relación presenta la distribución de IPODs por localidad:

`r ipods[,c(-1,-7)]`

## ¿En qué condición se encuentran los equipos? 
#### ¿cómo medimos la salud del parque operativo?

Snipe-IT no maneja de forma natural un campo para la condición o estado de los equipos. Sin embargo, permite la creación de *custom fields* o campos customizados. Hemos creado un campo *condition* asignado a los IPODs, que toma valores según los siguientes criterios:

5 - Nuevo (no desplegado). 

4 - Nuevo (desplegado). En excelente condiciones. 

3 - En buenas condiciones. Su rendimiento es el esperado.

2 - En condiciones deficientes. Rendimiento disminuido. Presenta fallos.

1 - En malas condiciones. No rinde lo esperado. No funciona.

0 - Dañado. Descartado.



        